version: '3.1'
name: dna-node-processor

services:

###########################################################################
########################### DNA_NODE_PROCESSOR ############################
###########################################################################
  dna-node-processor:
    container_name: 'dna-node-server'
    image: kwlee0220/dna-node
    volumes:
      - ./dna.node:/dna.node
      - ./torch_hub:/root/.cache/torch/hub
    environment:
      DNA_NODE_FFMPEG_PATH: "/opt/conda/bin/ffmpeg"
      DISPLAY: "${DISPLAY}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - default
      - dna_server_net
#    command: dna_node_server --conf_root conf/etri_testbed --redis redis://localhost:6379?db=0 --req_channel track-requests --show
		command: /bin/bash
    restart: always

networks:
  dna_server_net:
    external: true
    internal: true
